name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd test
            cd ${{secrets.SERVICE_NAME}}
            pm2 stop app
            pm2 start "npm run start" --name "app"
            git pull
            echo 'Deloyment successful'
